name: 'Publish-GHCR'
description: 'Builds and pushes a Docker image to GHCR with automated metadata'

inputs:
  registry:
    required: true
  image_name:
    required: true
  image_tag:
    required: false
  dockerfile:
    default: docker/Dockerfile
  context:
    default: '.'

outputs:
  digest:
    description: "Digest of the pushed image"
    value: ${{ steps.push.outputs.digest }}

runs:
  using: 'composite'

  steps:

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=ref,event=tag
          type=sha
          type=edge,branch=main
        labels: |
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ github.ref_name }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{ github.ref_name }}
          COMMIT=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ inputs.registry }}/${{ inputs.image_name }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
