name: NPM Version Bump
description: 'Bumps version with npm and pushes to github'

inputs:
  version:
    description: 'Version (pre(patch/minor/major), prerelease, release)'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: 'package.json'

    - name: Update npm version in package.json
      shell: bash
      env:
        NPM_VERSION: ${{ inputs.version }}
      run: |
        # Add as GitHub actions bot
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        npm version "$NPM_VERSION" --preid=rc --no-git-tag-version
        NEW_VERSION=$(npm pkg get version | tr -d '"')
        git add package.json package-lock.json
        git commit -m "chore: bump version to v${NEW_VERSION}"

    - name: Push version bump
      shell: bash
      run: |
        git push

