name: Reusable Markdownlint

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  markdownlint-pipeline:
    name: Markdownlint Pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # important for git diff comparisons
          persist-credentials: false

      - name: Run Markdownlint
        uses: open-crypto-broker/.github/actions/markdownlint@main # nolint # zizmor: ignore[unpinned-uses]
